### ISSUE TITLE
error when trying to generate hash

### ISSUE THREAD

**Issue by pwnedDesal** [GhostPack/Rubeus#160]
`./Rubeus.exe hash /password:123456 /user:fake01 /domain:nukesec.lab`

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Rubeus.Crypto.KerberosPasswordHash(KERB_ETYPE etype, String password, String salt, Int32 count)
   at Rubeus.Crypto.ComputeAllKerberosPasswordHashes(String password, String userName, String domainName)
   at Rubeus.Commands.Hash.Execute(Dictionary`2 arguments)
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Rubeus.Program.MainExecute(String commandName, Dictionary`2 parsedArgs)
   at Rubeus.Program.Main(String[] args)

**Comment by 0xe7** [comment]
what version of Rubeus are you using because it seems to work fine for me using the current version:

```
C:\temp>.\Rubeus.exe hash /password:123456 /user:fake01 /domain:nukesec.lab

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v2.2.3


[*] Action: Calculate Password Hash(es)

[*] Input password             : 123456
[*] Input username             : fake01
[*] Input domain               : nukesec.lab
[*] Salt                       : NUKESEC.LABfake01
[*]       rc4_hmac             : 32ED87BDB5FDC5E9CBA88547376818D4
[*]       aes128_cts_hmac_sha1 : 9F2FDBE3548D0995D03C1C4597D01397
[*]       aes256_cts_hmac_sha1 : 6CADA2FE82650C12F04D17AB77C79E02ED68D7169CA45432A48E7FC678DBAC63
[*]       des_cbc_md5          : ADAD1FE36D4C854F
```

**Comment by pwnedDesal** [comment]
Hi, i am using current version. I also tried rubues with administrator
account same error is occured

**Comment by 0xe7** [comment]
This is really odd, how is it that you are running Rubeus?
