### ISSUE TITLE
Windows 7 x32 error

### ISSUE THREAD

**Issue by 0xRCA** [GhostPack/Rubeus#27]
Is x32 systems supported?
running 
`dump`
on Windows 7 x32 gives 
`[X] Error 87 calling LsaCallAuthenticationPackage for target ... : The parameter is incorrect. `
both compiling AnyCpu and x86.
Seems like KERB_RETRIEVE_TKT_REQUEST structure size error.

**Comment by ivanou2017** [comment]
KERB_RETRIEVE_TKT_REQUEST structure size is correct,
seems like LSA.cs line 1129 error
`Marshal.WriteIntPtr(unmanagedAddr, 24, newTargetNameBuffPtr);  `

**Comment by ivanou2017** [comment]
should be 
`Marshal.WriteIntPtr(unmanagedAddr, 16, newTargetNameBuffPtr);` on x32 systems

**Comment by 0xRCA** [comment]
`hash `
function also not working on x32 machines =(

**Comment by bytecod3r** [comment]
did you find a way to solve this?

I'm getting the below on win7x86..


```
Rubeus.exe kerberoast /domain:TEST.COM /rc4opsec


   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2


[*] Action: Kerberoasting

[*] Using 'tgtdeleg' to request a TGT for the current user

[X] Error 87 calling LsaCallAuthenticationPackage() for target "cifs/TESTSERVER.TEST.COM" : The parameter is incorrect
[X] Error: Unable to extract session key from cache for target SPN: cifs/TESTSERVER.TEST.COM

[!] Unhandled Rubeus exception:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubeus.KRB_CRED..ctor(Byte[] bytes)
   at Rubeus.Roast.Kerberoast(String spn, String userName, String OUName, String domain, String dc, NetworkCredential cred, String outFile, KRB_CRED TGT, Boolean useTGTdeleg, String suppor$
   at Rubeus.Commands.Kerberoast.Execute(Dictionary`2 arguments)
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Rubeus.Program.Main(String[] args)

```

**Comment by HarmJ0y** [comment]
I'll look into this as soon as I have time.

**Comment by HarmJ0y** [comment]
Now that Windows 7 has been officially end of lifed, I'm going to close this.
