### ISSUE TITLE
Unhandled Rubeus exception

### ISSUE THREAD

**Issue by doubley612** [GhostPack/Rubeus#42]
I'm executing: 
`Rubeus.exe kerberoast /rc4opsec`

After a lot of tickets are retrieved I'm getting the following exception:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubeus.Roast.Kerberoast(String spn, String userName, String OUName, String domain, String dc, NetworkCredential cred, String outFile, Boolean simpleOutput, KRB_CRED TGT, Boolean useTGTdeleg, String supportedEType, String pwdSetAfter, String pwdSetBefore, String ldapFilter, Int32 resultLimit, Boolean userStats)
   at Rubeus.Commands.Kerberoast.Execute(Dictionary`2 arguments)
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Rubeus.Program.MainExecute(String commandName, Dictionary`2 parsedArgs)`

**Comment by HarmJ0y** [comment]
Can you retry this with the current branch? I'm hoping that https://github.com/GhostPack/Rubeus/commit/f7c614e026b3a4c9ce9081f79110cf4e9c4a7493 fixed it.

**Comment by wh1tenoise** [comment]
I just cloned the repository today and still get the exception.

Command
`.\Rubeus.exe kerberoast /outfile:hashes.txt /format:hashcat /domain:[DOMAIN] /dc:[DC_HOST_NAME]`

Exception
`[!] Unhandled Rubeus exception:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubeus.Roast.Kerberoast(String spn, List`1 spns, String userName, String OUName, String domain, String dc, NetworkCredential cred, String outFile, Boolean simpleOutput, KRB_CRED TGT, Boolean useTGTdeleg, String supportedEType, String pwdSetAfter, String pwdSetBefore, String ldapFilter, Int32 resultLimit, Boolean userStats, Boolean enterprise)
   at Rubeus.Commands.Kerberoast.Execute(Dictionary`2 arguments)
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Rubeus.Program.MainExecute(String commandName, Dictionary`2 parsedArgs)`

**Comment by FuzzySecurity** [comment]
@HarmJ0y I think this is replicating
https://github.com/GhostPack/Rubeus/pull/49

In Roast.Kerberoast, here:
https://github.com/GhostPack/Rubeus/blob/master/Rubeus/lib/Roast.cs#L609

I had a similar issue and patching in the extended error handling from PR 49 worked. See pre/post patch execution on my local non-joined machine.
![image](https://user-images.githubusercontent.com/10997340/94264716-193a0500-ff2f-11ea-891a-bc743e48329f.png)

**Comment by FreeDurok** [comment]
mee too, have same exception:

![image](https://user-images.githubusercontent.com/43138030/94934206-b5ce4b00-04cb-11eb-8305-65e114f35ec9.png)
