### ISSUE TITLE
Error/Dump with asktgt in Rubeus 2.0

### ISSUE THREAD

**Issue by nowhey2** [GhostPack/Rubeus#90]
If I run an asktgt using certificates (i.e., smartcard): asktgt /user:<user> /domain:<fqdn> /dc:<dc3> /certificate:<thumbprint> /password:<pin> /ptt, where the <> fields in the previous example have been sanitized, the following error happens in Rubeus 2.0 (and a few versions previously):

[*] Action: Ask TGT
[!] Unhandled Rubeus exception:

System.Security.Cryptography.CryptographicException: Cannot find the requested object.
   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.X509Certificates.X509Utils._QueryCertBlobType(Byte[] rawData)
   at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromBlob(Byte[] rawData, Object password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password)
   at Rubeus.Ask.TGT(String userName, String domain, String certFile, String certPass, KERB_ETYPE etype, String outfile, Boolean ptt, String domainController, LUID luid, Boolean describe, Boolean verifyCerts, String servicekey, Boolean getCredentials)
   at Rubeus.Commands.Asktgt.Execute(Dictionary`2 arguments)
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Rubeus.Program.MainExecute(String commandName, Dictionary`2 parsedArgs)

If the same exact command is run with v1.5.0 it works as expected (when the certificate support was added).  I started noticing this around v1.7.0 and hoped it would be noticed/reported, but since it hasn't, here we are.

**Comment by 0xe7** [comment]
looks like PR #91 should fix this, should be merged soonish

**Comment by HarmJ0y** [comment]
@nowhey2 can you verify if this fixed the issue?

**Comment by ohsabrie** [comment]
I think i got quite the same issue with the similar command, with a build from 3 days ago (#91) 

./rubeus.exe asktgt /user:osabrie /certificate:c:\users\test_ospki\desktop\os.pfx /password:123 /ptt
   ______        _                      
  (_____ \      | |                     
   _____) )_   _| |__  _____ _   _  ___ 
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v2.0.0 

[*] Action: Ask TGT

[*] Using PKINIT with etype rc4_hmac and subject: CN=REDACTED, DC=com 
[*] Building AS-REQ (w/ PKINIT preauth) for: 'redacted'
[+] TGT request successful!

[!] Unhandled Rubeus exception:

Asn1.AsnException: trailing garbage
   à Asn1.AsnElt.Decode(Byte[] buf, Int32 off, Int32 len, Boolean exactLength)
   à Asn1.AsnElt.Decode(Byte[] buf)
   à Rubeus.Ask.HandleASREP(AsnElt responseAsn, KERB_ETYPE etype, String keyString, String outfile, Boolean ptt, LUID luid, Boolean describe, Boolean verbose, AS_REQ asReq, String serviceKey, Boolean getCredentials, String dcIP)
   à Rubeus.Ask.InnerTGT(AS_REQ asReq, KERB_ETYPE etype, String outfile, Boolean ptt, String domainController, LUID luid, Boolean describe, Boolean verbose, Boolean opsec, String serviceKey, Boolean getCredentials)
   à Rubeus.Ask.TGT(String userName, String domain, String certFile, String certPass, KERB_ETYPE etype, String outfile, Boolean ptt, String domainController, LUID luid, Boolean describe, Boolean verifyCerts, String servicekey, Boolean getCredentials)
   à Rubeus.Commands.Asktgt.Execute(Dictionary`2 arguments)
   à Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   à Rubeus.Program.MainExecute(String commandName, Dictionary`2 parsedArgs)

**Comment by nowhey2** [comment]
I'll do a pull and check.

**Comment by Dcellular** [comment]
I encountered this problem in a similar manner with `Rubeus.exe asktgt /user:userName /certificate: cert.pfx` in a lab environment and found that authentication on the Domain Controller had broken in some way. Rebooting the DC resolved this for me.

Hope this helps.

**Comment by winsecurity** [comment]
```
PS C:\Users\test1\Desktop> .\Rubeus.exe asktgt /user:Administrator /certificate:C:\Users\test1\Desktop\cert.pfx /password:abc

[*] Action: Ask TGT


[!] Unhandled Rubeus exception:

System.Security.Cryptography.CryptographicException: The specified network password is not correct.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.X509Certificates.X509Utils._LoadCertFromFile(String fileName, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle& pCertCtx)
   at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at Rubeus.Ask.FindCertificate(String certificate, String storePassword)
   at Rubeus.Ask.TGT(String userName, String domain, String certFile, String certPass, KERB_ETYPE etype, String outfile, Boolean ptt, String domainController, LUID luid, Boolean describe, Boolean verifyCerts, String servicekey, Boolean getCredentials, String proxyUrl)
   at Rubeus.Commands.Asktgt.Execute(Dictionary`2 arguments)
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Rubeus.Program.MainExecute(String commandName, Dictionary`2 parsedArgs)
```

I am also getting the same error on latest build. rebooting the DC did not help. issue got solved for anyone?

**Comment by winsecurity** [comment]
sorry, it got fixed. the error is in openssl generation of pfx file in kali linux.
i added -legacy option and now rubeus is working

**Comment by CX330Blake** [comment]
> sorry, it got fixed. the error is in openssl generation of pfx file in kali linux. i added -legacy option and now rubeus is working

Yeah this solved my problem, thx.
